version: '3'
services:
    app:
        build:
            context: .
            dockerfile: .docker/app.docker
        volumes:
            - .:/var/www/html
        environment:
            - 'DB_HOST=db'
    db:
        image: mysql:5.7
        volumes:
            - ./storage/app/db:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            - 'MYSQL_ROOT_PASSWORD=root'
    web:
        build:
            context: .
            dockerfile: .docker/web.docker
        volumes:
            - .:/var/www/html
        ports:
            - '443:443'
        links:
            - app